title: Abhiram Mannam # your name (or website title) here
logo: "/images/the-university-of-utah1230.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

I'm Abhiram Mannam, a data scientist and analyst. I was born in India, but I currently live in the USA. My formal education as an engineer included programming and machine learning, so as a result, I was more focused on analytical thinking and learning new things.  
  <br><br>
I am pursuing an MS in Business Analytics at David Eccles School of Business, University of Utah.
<br> <br>
<a href="https://www.linkedin.com/in/abhiram-mannam/">View My LinkedIn Profile</a>  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

